# Generated by Django 5.2.3 on 2025-06-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="no_commercial_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
