# Generated by Django 5.2.3 on 2025-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agreed_tos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="no_commercial_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
