# Generated by Django 5.2.3 on 2025-06-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_responsible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={
                "permissions": [
                    ("assign_responsible", "Can assign responsible user to property")
                ]
            },
        ),
    ]
