# Generated by Django 5.2.3 on 2025-06-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_property_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="facilities",
            new_name="amenities",
        ),
    ]
