# Generated by Django 5.2.3 on 2025-06-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_property_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="property_videos/"),
        ),
    ]
