# Generated by Django 5.2.3 on 2025-06-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_add_video_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
